<template>
  <div>
    <el-card class="stat-card">
      <stat-content :statList="statList" ref="swiper1" :reportTime="reportTime" :customSlidesPerView="3"></stat-content>
    </el-card>
  </div>
</template>

<script setup>
const reportTime = ref('1709615400000')
const statList = ref([
  {
    modelId: 1669,
    deviceCode: 'test16080957_1',
    deviceName: '金盆来水',
    templateId: 283,
    elementIdentify: 'flow',
    elementName: '流量',
    elementUnit: 'm³/s',
    elementType: 'double',
    keyNum: 0,
    elementFormula: null,
    elementKey: 'ff_flow',
    dataValue: '0.83',
    decimal: null,
    reserveDigits: 2,
    enumValue: null,
    factorTypeName: '综合',
    reportedTime: 1709615400000,
    leakageEnvironment: null,
    deviceModel: null,
    pressureEnvironment: null,
    stationId: null,
    state: null,
    dataState: null,
    elementShow: '1',
    alarmData: null,
    productType: null,
  },
  {
    modelId: 1668,
    deviceCode: 'test16080957_1',
    deviceName: '金盆来水',
    templateId: 283,
    elementIdentify: 'liquid_level',
    elementName: '液位',
    elementUnit: 'm',
    elementType: 'double',
    keyNum: 0,
    elementFormula: null,
    elementKey: 'ff_liquid_level',
    dataValue: '0.52',
    decimal: null,
    reserveDigits: 2,
    enumValue: null,
    factorTypeName: '综合',
    reportedTime: 1709615400000,
    leakageEnvironment: null,
    deviceModel: null,
    pressureEnvironment: null,
    stationId: null,
    state: null,
    dataState: null,
    elementShow: '1',
    alarmData: null,
    productType: null,
  },
  {
    modelId: 1667,
    deviceCode: 'test16080957_1',
    deviceName: '金盆来水',
    templateId: 283,
    elementIdentify: 'water_temperature',
    elementName: '水温',
    elementUnit: '℃',
    elementType: 'double',
    keyNum: 0,
    elementFormula: null,
    elementKey: 'ff_temperature',
    dataValue: '26.50',
    decimal: null,
    reserveDigits: 2,
    enumValue: null,
    factorTypeName: '综合',
    reportedTime: 1709615400000,
    leakageEnvironment: null,
    deviceModel: null,
    pressureEnvironment: null,
    stationId: null,
    state: null,
    dataState: null,
    elementShow: '1',
    alarmData: null,
    productType: null,
  },
  {
    modelId: 1666,
    deviceCode: 'test16080957_1',
    deviceName: '金盆来水',
    templateId: 283,
    elementIdentify: 'water_turbidity',
    elementName: '浊度',
    elementUnit: 'NTU',
    elementType: 'double',
    keyNum: 0,
    elementFormula: null,
    elementKey: 'ff_water_turbidity',
    dataValue: '2.40',
    decimal: null,
    reserveDigits: 2,
    enumValue: null,
    factorTypeName: '综合',
    reportedTime: 1709615400000,
    leakageEnvironment: null,
    deviceModel: null,
    pressureEnvironment: null,
    stationId: null,
    state: null,
    dataState: null,
    elementShow: '1',
    alarmData: null,
    productType: null,
  },
  {
    modelId: 1665,
    deviceCode: 'test16080957_1',
    deviceName: '金盆来水',
    templateId: 283,
    elementIdentify: 'water_ph',
    elementName: 'PH',
    elementUnit: null,
    elementType: 'double',
    keyNum: 0,
    elementFormula: null,
    elementKey: 'ff_water_ph',
    dataValue: '7.86',
    decimal: null,
    reserveDigits: 2,
    enumValue: null,
    factorTypeName: '综合',
    reportedTime: 1709615400000,
    leakageEnvironment: null,
    deviceModel: null,
    pressureEnvironment: null,
    stationId: null,
    state: null,
    dataState: null,
    elementShow: '1',
    alarmData: null,
    productType: null,
  },
])
</script>

<style lang="scss" scoped></style>
