/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    HelloWorld: (typeof import('./../components/HelloWorld.vue'))['default']
    IEpAddLocation: (typeof import('~icons/ep/add-location'))['default']
    IEpAim: (typeof import('~icons/ep/aim'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SvgIcon: (typeof import('./../components/SvgIcon/index.vue'))['default']
    TestA: (typeof import('./../components/TestA/index.vue'))['default']
  }
}
